sudo: false
language: node_js
node_js:
  - '10'
addons:
  apt:
    packages:
      - xvfb
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm i -g yarn
  - yarn update
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn
script:
  - yarn coveralls
